version: "3.6"
services:
    web:
        image: "gitlab/gitlab-ee:latest"
        restart: always
        hostname: "${HOST_NAME}"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url "${URL}"
                # Add any other gitlab.rb configuration here, each on its own line
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
            - "${SSH_PORT}:22"
        volumes:
            - "./gitlab-ee/config:/etc/gitlab"
            - "./gitlab-ee/logs:/var/log/gitlab"
            - "./gitlab-ee/data:/var/opt/gitlab"
        networks:
            - "git_network"
    runner:
        image: "gitlab/gitlab-runner:latest" # for debugging purposes
        # image: "gitlab/gitlab-runner:alpine" # smaller footprint, good for production
        restart: "always"
        container_name: "gitlab-runner"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./runner/config:/etc/gitlab-runner"
networks:
    git_network:
        driver: "bridge"