version: "3.6"
services:
    web:
        image: 'gitlab/gitlab-ee:latest'
        restart: always
        hostname: '${HOST_NAME}'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url '${URL}'
                # Add any other gitlab.rb configuration here, each on its own line
        ports:
        - '${HTTP_PORT}:80'
        - '${HTTPS_PORT}:443'
        - '${SSH_PORT}:22'
        volumes:
        - 'config:/etc/gitlab'
        - 'logs:/var/log/gitlab'
        - 'data:/var/opt/gitlab'
volumes:
    config:
        driver: local
    logs:
        driver: local
    data:
        driver: local