version: "3.6"
services:
    web:
        container_name: "gitlab-ee"
        image: "gitlab/gitlab-ee:latest"
        restart: always
        hostname: "${HOST_NAME}"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url "${URL}"
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = "${SMTP_ADDRESS:-smtp.gmail.com}"
                gitlab_rails['smtp_port'] = ${SMTP_PORT:-587}
                gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
                # unsecured method, find a better way.
                gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}" 
                gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN:-smtp.gmail.com}"
                gitlab_rails['smtp_authentication'] = "login"
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls'] = false
                # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert',
                # see http://api.rubyonrails.org/classes/ActionMailer/Base.html
                gitlab_rails['smtp_openssl_verify_mode'] = 'peer' 
                # Add any other gitlab.rb configuration here, each on its own line
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
            - "${SSH_PORT}:22"
        volumes:
            - "./gitlab-ee/config:/etc/gitlab"
            - "./gitlab-ee/logs:/var/log/gitlab"
            - "./gitlab-ee/data:/var/opt/gitlab"
        networks:
            - "git_network"
    runner:
        image: "gitlab/gitlab-runner:latest" # for debugging purposes
        # image: "gitlab/gitlab-runner:alpine" # smaller footprint, good for production
        restart: "always"
        container_name: "gitlab-runner"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./runner/config:/etc/gitlab-runner"
        networks:
            - "git_network"
networks:
    git_network:
        driver: "bridge"
